name: gdluxx-dev

services:
  gdluxx:
    build: .
    image: gdluxx-dev
    container_name: gdluxx-dev
    ports:
      - '7765:7755'
    volumes:
      - ./data:/app/data
      # - /host/path/to/downloads:/app/downloads
    environment:
      # - PORT=${PORT}
      # - HOST=${HOST}
      - AUTH_SECRET=${AUTH_SECRET}
      - ORIGIN=${ORIGIN:-http://localhost:7755}
      # - DOWNLOAD_PATH=/app/downloads
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 3s
