name: gdluxx

services:
  gdluxx:
    build: .
    image: gdluxx
    container_name: gdluxx
    ports:
      - '7755:7755'
    volumes:
      - ./data:/app/data
    environment:
      # - PORT=${PORT}
      # - HOST=${HOST}
      - AUTH_SECRET=${AUTH_SECRET}
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 3s
