name: gdluxx

services:
  gdluxx:
    image: ghcr.io/gdluxx/gdluxx:latest
    container_name: gdluxx
    ports:
      - '7755:7755'
    volumes:
      - ./data:/app/data
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - ORIGIN=${ORIGIN:-http://localhost:7755}
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 3s
