name: gdluxx

services:
  gdluxx:
    image: ghcr.io/gdluxx/gdluxx:latest
    container_name: gdluxx
    user: '1000:1000'
    ports:
      - '7755:7755'
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - HOST=${HOST}
      - AUTH_SECRET=${AUTH_SECRET}
    restart: unless-stopped
